name: rapids_mortgage_dashboard
channels:
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - plotly=4.5
  - cudf=0.12
  - dash=1.8
  - pandas=0.25.3
  - cupy=7.1
  - datashader=0.10
  - dask-cuda=0.12.0
  - dash-daq=0.3.2
  - gunicorn=20.0
